[aion]
chain = "amity/amity.json"

[account]
stake_contract = "0xa056337bb14e818f3f53e13ab0d93b6539aa570cba91ce65c716058241989be9"

[network]
max_peers = 32
net_id = 28
local_node = "p2p://00000000-0000-0000-0000-000000000000@0.0.0.0:30303"
boot_nodes = [
"p2p://a8010211-8c7e-496c-9c4e-c89318280274@52.170.207.75:30303",
"p2p://a8020211-729a-4584-86f1-e19ab97cf9ce@13.95.31.156:30303",
"p2p://a8030211-729a-4584-86f1-e19ab97cf9cq@104.155.165.18:30303",
"p2p://a8040211-8c7e-496c-9c4e-c89318280275@35.228.32.193:30303"
]
ip_black_list = []

[http]
disable = false
port = 8545

[websockets]
disable = true

[ipc]
disable = true

[stratum]
disable = true
port = 8008
interface = "0.0.0.0"

[mining]
author = "0xa07e185919beef1e0a79fea78fcfabc24927c5067d758e514ad74b905a2bf137"
#staker_private_key = "0xcc76648ce8798bc18130bc9d637995e5c42a922ebeab78795fac58081b9cf9d4"