# Usage:
# encoder pattern:
# d: date, l: log level, t: target, L: line, m: message, n: new line

refresh_rate: 60 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {t}: {m}{n}"
  vm_log:
    kind: rolling_file
    path: "logs/vm.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 30
        pattern: "logs/vm.log.{}.gz"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {t}:{L} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
loggers:
  vm:
    level: debug
    appenders:
      - vm_log
    additive: false
  sync:
    level: info
    appenders:
      - stdout
    additive: false
  rpc:
    level: warn
    appenders:
      - stdout
    additive: false