[package]
name = "fixed-point"
version = "0.1.0"
authors = ["Aion Foundation <admin@aion.network>"]

[dependencies]
num-bigint = "0.2"
bigdecimal = "0.1.0"
num-traits = "0.2.5"
lazy_static = "1.3.0"

[dev-dependencies]
rand = "0.4"