[package]
name = "ajson"
version = "0.1.0"
authors = ["Aion Foundation <admin@aion.network>"]

[dependencies]
aion-types = { path = "../util/aion-types"}
ethbloom = { path = "../util/ethbloom"}
rustc-hex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

