[package]
name = "util-error"
version = "0.1.0"
authors = ["Aion Foundation <admin@aion.network>"]

[dependencies]
rlp = { path = "../rlp" }
db = { path = "../../db/core" }
aion-types = { path = "../../util/aion-types"}
error-chain = { version = "0.12", default-features = false }
rustc-hex = "1.0"
