[package]
name = "solidity"
version = "0.2.0"
authors = ["Admin <admin@aion.network>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
log = "0.3"
serde_json = "1.0.31"

[build-dependencies]
cmake = "0.1"
target_info = "0.1"
