[package]
name = "crypto"
version = "0.1.0"
authors = ["aion <admin@aion.network>"]
build = "build.rs"

[build-dependencies]
gcc = "^0.3"

[dependencies]
rustc-serialize = "^0.3"
rand = "*"
time = "*"
libc = "*"
aion-types = { path = "../../util/aion-types"}
subtle = "1.0.0"
